mod stop_recording;
pub use stop_recording::StopRecording;
pub use stop_recording::StopRecordingRequest;
pub use stop_recording::StopRecordingResponse;
mod start_gmcm_recording;
pub use start_gmcm_recording::StartGmcmRecording;
pub use start_gmcm_recording::StartGmcmRecordingRequest;
pub use start_gmcm_recording::StartGmcmRecordingResponse;
mod start_gvm_recording;
pub use start_gvm_recording::StartGvmRecording;
pub use start_gvm_recording::StartGvmRecordingRequest;
pub use start_gvm_recording::StartGvmRecordingResponse;
mod set_camera;
pub use set_camera::SetCamera;
pub use set_camera::SetCameraRequest;
pub use set_camera::SetCameraResponse;
