use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct SbgStatusCom {
    pub port_a: bool,
    pub port_b: bool,
    pub port_c: bool,
    pub port_d: bool,
    pub port_e: bool,
    pub port_a_rx: bool,
    pub port_a_tx: bool,
    pub port_b_rx: bool,
    pub port_b_tx: bool,
    pub port_c_rx: bool,
    pub port_c_tx: bool,
    pub port_d_rx: bool,
    pub port_d_tx: bool,
    pub port_e_rx: bool,
    pub port_e_tx: bool,
    pub eth_0: bool,
    pub eth_1: bool,
    pub eth_2: bool,
    pub eth_3: bool,
    pub eth_4: bool,
    pub eth_0_rx: bool,
    pub eth_0_tx: bool,
    pub eth_1_rx: bool,
    pub eth_1_tx: bool,
    pub eth_2_rx: bool,
    pub eth_2_tx: bool,
    pub eth_3_rx: bool,
    pub eth_3_tx: bool,
    pub eth_4_rx: bool,
    pub eth_4_tx: bool,
    pub can_rx: bool,
    pub can_tx: bool,
    pub can_status: u8,
}

impl Default for SbgStatusCom {
    fn default() -> Self {
        SbgStatusCom {
            port_a: false,
            port_b: false,
            port_c: false,
            port_d: false,
            port_e: false,
            port_a_rx: false,
            port_a_tx: false,
            port_b_rx: false,
            port_b_tx: false,
            port_c_rx: false,
            port_c_tx: false,
            port_d_rx: false,
            port_d_tx: false,
            port_e_rx: false,
            port_e_tx: false,
            eth_0: false,
            eth_1: false,
            eth_2: false,
            eth_3: false,
            eth_4: false,
            eth_0_rx: false,
            eth_0_tx: false,
            eth_1_rx: false,
            eth_1_tx: false,
            eth_2_rx: false,
            eth_2_tx: false,
            eth_3_rx: false,
            eth_3_tx: false,
            eth_4_rx: false,
            eth_4_tx: false,
            can_rx: false,
            can_tx: false,
            can_status: 0,
        }
    }
}

impl crate::Message for SbgStatusCom {}
