use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct INSNavCart {
    pub header: crate::std_msgs::msg::Header,
    pub block_header: crate::septentrio_gnss_driver::msg::BlockHeader,
    pub gnss_mode: u8,
    pub error: u8,
    pub info: u16,
    pub gnss_age: u16,
    pub x: f64,
    pub y: f64,
    pub z: f64,
    pub accuracy: u16,
    pub latency: u16,
    pub datum: u8,
    pub sb_list: u16,
    pub x_std_dev: f32,
    pub y_std_dev: f32,
    pub z_std_dev: f32,
    pub xy_cov: f32,
    pub xz_cov: f32,
    pub yz_cov: f32,
    pub heading: f32,
    pub pitch: f32,
    pub roll: f32,
    pub heading_std_dev: f32,
    pub pitch_std_dev: f32,
    pub roll_std_dev: f32,
    pub heading_pitch_cov: f32,
    pub heading_roll_cov: f32,
    pub pitch_roll_cov: f32,
    pub vx: f32,
    pub vy: f32,
    pub vz: f32,
    pub vx_std_dev: f32,
    pub vy_std_dev: f32,
    pub vz_std_dev: f32,
    pub vx_vy_cov: f32,
    pub vx_vz_cov: f32,
    pub vy_vz_cov: f32,
}

impl Default for INSNavCart {
    fn default() -> Self {
        INSNavCart {
            header: crate::std_msgs::msg::Header::default(),
            block_header: crate::septentrio_gnss_driver::msg::BlockHeader::default(),
            gnss_mode: 0,
            error: 0,
            info: 0,
            gnss_age: 0,
            x: 0.0,
            y: 0.0,
            z: 0.0,
            accuracy: 0,
            latency: 0,
            datum: 0,
            sb_list: 0,
            x_std_dev: 0.0,
            y_std_dev: 0.0,
            z_std_dev: 0.0,
            xy_cov: 0.0,
            xz_cov: 0.0,
            yz_cov: 0.0,
            heading: 0.0,
            pitch: 0.0,
            roll: 0.0,
            heading_std_dev: 0.0,
            pitch_std_dev: 0.0,
            roll_std_dev: 0.0,
            heading_pitch_cov: 0.0,
            heading_roll_cov: 0.0,
            pitch_roll_cov: 0.0,
            vx: 0.0,
            vy: 0.0,
            vz: 0.0,
            vx_std_dev: 0.0,
            vy_std_dev: 0.0,
            vz_std_dev: 0.0,
            vx_vy_cov: 0.0,
            vx_vz_cov: 0.0,
            vy_vz_cov: 0.0,
        }
    }
}

impl crate::Message for INSNavCart {}
