mod add_two_ints;
pub use add_two_ints::AddTwoInts;
pub use add_two_ints::AddTwoIntsRequest;
pub use add_two_ints::AddTwoIntsResponse;
mod set_bool;
pub use set_bool::SetBool;
pub use set_bool::SetBoolRequest;
pub use set_bool::SetBoolResponse;
mod trigger;
pub use trigger::Trigger;
pub use trigger::TriggerRequest;
pub use trigger::TriggerResponse;
