use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct BrakeReport {
    pub header: crate::std_msgs::msg::Header,
    pub cmd_type: u8,
    pub pressure_input: f32,
    pub pressure_cmd: f32,
    pub pressure_output: f32,
    pub torque_input: f32,
    pub torque_cmd: f32,
    pub torque_output: f32,
    pub accel_cmd: f32,
    pub accel_output: f32,
    pub percent_input: f32,
    pub percent_cmd: f32,
    pub percent_output: f32,
    pub btsi_cmd: bool,
    pub yield_request: bool,
    pub limiting_value: bool,
    pub limiting_rate: bool,
    pub external_control: bool,
    pub ready: bool,
    pub enabled: bool,
    pub override_active: bool,
    pub override_other: bool,
    pub override_latched: bool,
    pub timeout: bool,
    pub fault: bool,
    pub bad_crc: bool,
    pub bad_rc: bool,
    pub degraded: bool,
    pub limit_value: f32,
    pub brake_available_duration: f32,
    pub brake_available_full: bool,
    pub req_shift_park: bool,
    pub req_park_brake: bool,
    pub external_button: bool,
    pub comms_loss_armed: bool,
    pub cmd_src: crate::ds_dbw_msgs::msg::CmdSrc,
}

impl Default for BrakeReport {
    fn default() -> Self {
        BrakeReport {
            header: crate::std_msgs::msg::Header::default(),
            cmd_type: 0,
            pressure_input: 0.0,
            pressure_cmd: 0.0,
            pressure_output: 0.0,
            torque_input: 0.0,
            torque_cmd: 0.0,
            torque_output: 0.0,
            accel_cmd: 0.0,
            accel_output: 0.0,
            percent_input: 0.0,
            percent_cmd: 0.0,
            percent_output: 0.0,
            btsi_cmd: false,
            yield_request: false,
            limiting_value: false,
            limiting_rate: false,
            external_control: false,
            ready: false,
            enabled: false,
            override_active: false,
            override_other: false,
            override_latched: false,
            timeout: false,
            fault: false,
            bad_crc: false,
            bad_rc: false,
            degraded: false,
            limit_value: 0.0,
            brake_available_duration: 0.0,
            brake_available_full: false,
            req_shift_park: false,
            req_park_brake: false,
            external_button: false,
            comms_loss_armed: false,
            cmd_src: crate::ds_dbw_msgs::msg::CmdSrc::default(),
        }
    }
}

impl crate::Message for BrakeReport {}
