use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct BrakeDiagnostics {
    pub header: crate::std_msgs::msg::Header,
    pub degraded: bool,
    pub degraded_cmd_type: bool,
    pub degraded_comms: bool,
    pub degraded_comms_dbw: bool,
    pub degraded_comms_dbw_gateway: bool,
    pub degraded_comms_dbw_steer: bool,
    pub degraded_comms_dbw_thrtl: bool,
    pub degraded_comms_dbw_gear: bool,
    pub degraded_comms_vehicle: bool,
    pub degraded_comms_actuator: bool,
    pub degraded_comms_actuator_1: bool,
    pub degraded_comms_actuator_2: bool,
    pub degraded_internal: bool,
    pub degraded_control_performance: bool,
    pub degraded_param_mismatch: bool,
    pub degraded_btsi_stuck_low: bool,
    pub degraded_btsi_stuck_high: bool,
    pub degraded_vehicle: bool,
    pub degraded_vehicle_speed: bool,
    pub degraded_bped_feedback: bool,
    pub degraded_actuator: bool,
    pub degraded_actuator_1: bool,
    pub degraded_actuator_2: bool,
    pub degraded_actuator_aeb_deny: bool,
    pub degraded_actuator_warm: bool,
    pub degraded_calibration: bool,
    pub fault: bool,
    pub fault_power: bool,
    pub fault_comms: bool,
    pub fault_internal: bool,
    pub fault_vehicle: bool,
    pub fault_actuator: bool,
    pub fault_comms_dbw: bool,
    pub fault_comms_dbw_gateway: bool,
    pub fault_comms_dbw_steer: bool,
    pub fault_comms_dbw_thrtl: bool,
    pub fault_comms_dbw_gear: bool,
    pub fault_comms_vehicle: bool,
    pub fault_comms_actuator: bool,
    pub fault_comms_actuator_1: bool,
    pub fault_comms_actuator_2: bool,
    pub fault_vehicle_speed: bool,
    pub fault_actuator_acc_deny: bool,
    pub fault_actuator_pedal_sensor: bool,
    pub fault_bped_sensor_1: bool,
    pub fault_bped_sensor_2: bool,
    pub fault_bped_sensor_mismatch: bool,
    pub fault_actuator_1: bool,
    pub fault_actuator_2: bool,
    pub fault_control_performance: bool,
    pub fault_param_mismatch: bool,
    pub fault_param_limits: bool,
    pub fault_calibration: bool,
}

impl Default for BrakeDiagnostics {
    fn default() -> Self {
        BrakeDiagnostics {
            header: crate::std_msgs::msg::Header::default(),
            degraded: false,
            degraded_cmd_type: false,
            degraded_comms: false,
            degraded_comms_dbw: false,
            degraded_comms_dbw_gateway: false,
            degraded_comms_dbw_steer: false,
            degraded_comms_dbw_thrtl: false,
            degraded_comms_dbw_gear: false,
            degraded_comms_vehicle: false,
            degraded_comms_actuator: false,
            degraded_comms_actuator_1: false,
            degraded_comms_actuator_2: false,
            degraded_internal: false,
            degraded_control_performance: false,
            degraded_param_mismatch: false,
            degraded_btsi_stuck_low: false,
            degraded_btsi_stuck_high: false,
            degraded_vehicle: false,
            degraded_vehicle_speed: false,
            degraded_bped_feedback: false,
            degraded_actuator: false,
            degraded_actuator_1: false,
            degraded_actuator_2: false,
            degraded_actuator_aeb_deny: false,
            degraded_actuator_warm: false,
            degraded_calibration: false,
            fault: false,
            fault_power: false,
            fault_comms: false,
            fault_internal: false,
            fault_vehicle: false,
            fault_actuator: false,
            fault_comms_dbw: false,
            fault_comms_dbw_gateway: false,
            fault_comms_dbw_steer: false,
            fault_comms_dbw_thrtl: false,
            fault_comms_dbw_gear: false,
            fault_comms_vehicle: false,
            fault_comms_actuator: false,
            fault_comms_actuator_1: false,
            fault_comms_actuator_2: false,
            fault_vehicle_speed: false,
            fault_actuator_acc_deny: false,
            fault_actuator_pedal_sensor: false,
            fault_bped_sensor_1: false,
            fault_bped_sensor_2: false,
            fault_bped_sensor_mismatch: false,
            fault_actuator_1: false,
            fault_actuator_2: false,
            fault_control_performance: false,
            fault_param_mismatch: false,
            fault_param_limits: false,
            fault_calibration: false,
        }
    }
}

impl crate::Message for BrakeDiagnostics {}
