use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct GearDiagnostics {
    pub header: crate::std_msgs::msg::Header,
    pub degraded: bool,
    pub degraded_cmd_type: bool,
    pub degraded_comms: bool,
    pub degraded_comms_dbw: bool,
    pub degraded_comms_dbw_gateway: bool,
    pub degraded_comms_dbw_steer: bool,
    pub degraded_comms_dbw_brake: bool,
    pub degraded_comms_dbw_thrtl: bool,
    pub degraded_comms_vehicle: bool,
    pub degraded_comms_vehicle_1: bool,
    pub degraded_comms_vehicle_2: bool,
    pub degraded_comms_actuator: bool,
    pub degraded_comms_actuator_1: bool,
    pub degraded_comms_actuator_2: bool,
    pub degraded_internal: bool,
    pub degraded_control_performance: bool,
    pub degraded_param_mismatch: bool,
    pub degraded_vehicle: bool,
    pub degraded_vehicle_speed: bool,
    pub degraded_actuator: bool,
    pub degraded_gear_mismatch: bool,
    pub degraded_power: bool,
    pub degraded_calibration: bool,
    pub fault: bool,
    pub fault_power: bool,
    pub fault_comms: bool,
    pub fault_comms_dbw: bool,
    pub fault_comms_dbw_gateway: bool,
    pub fault_comms_dbw_steer: bool,
    pub fault_comms_dbw_brake: bool,
    pub fault_comms_dbw_thrtl: bool,
    pub fault_comms_vehicle: bool,
    pub fault_comms_vehicle_1: bool,
    pub fault_comms_vehicle_2: bool,
    pub fault_comms_actuator: bool,
    pub fault_comms_actuator_1: bool,
    pub fault_comms_actuator_2: bool,
    pub fault_internal: bool,
    pub fault_vehicle: bool,
    pub fault_vehicle_speed: bool,
    pub fault_actuator: bool,
    pub fault_actuator_config: bool,
    pub fault_param_mismatch: bool,
    pub fault_calibration: bool,
}

impl Default for GearDiagnostics {
    fn default() -> Self {
        GearDiagnostics {
            header: crate::std_msgs::msg::Header::default(),
            degraded: false,
            degraded_cmd_type: false,
            degraded_comms: false,
            degraded_comms_dbw: false,
            degraded_comms_dbw_gateway: false,
            degraded_comms_dbw_steer: false,
            degraded_comms_dbw_brake: false,
            degraded_comms_dbw_thrtl: false,
            degraded_comms_vehicle: false,
            degraded_comms_vehicle_1: false,
            degraded_comms_vehicle_2: false,
            degraded_comms_actuator: false,
            degraded_comms_actuator_1: false,
            degraded_comms_actuator_2: false,
            degraded_internal: false,
            degraded_control_performance: false,
            degraded_param_mismatch: false,
            degraded_vehicle: false,
            degraded_vehicle_speed: false,
            degraded_actuator: false,
            degraded_gear_mismatch: false,
            degraded_power: false,
            degraded_calibration: false,
            fault: false,
            fault_power: false,
            fault_comms: false,
            fault_comms_dbw: false,
            fault_comms_dbw_gateway: false,
            fault_comms_dbw_steer: false,
            fault_comms_dbw_brake: false,
            fault_comms_dbw_thrtl: false,
            fault_comms_vehicle: false,
            fault_comms_vehicle_1: false,
            fault_comms_vehicle_2: false,
            fault_comms_actuator: false,
            fault_comms_actuator_1: false,
            fault_comms_actuator_2: false,
            fault_internal: false,
            fault_vehicle: false,
            fault_vehicle_speed: false,
            fault_actuator: false,
            fault_actuator_config: false,
            fault_param_mismatch: false,
            fault_calibration: false,
        }
    }
}

impl crate::Message for GearDiagnostics {}
