use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ThrottleDiagnostics {
    pub header: crate::std_msgs::msg::Header,
    pub degraded: bool,
    pub degraded_cmd_type: bool,
    pub degraded_comms: bool,
    pub degraded_comms_dbw: bool,
    pub degraded_comms_dbw_gateway: bool,
    pub degraded_comms_dbw_steer: bool,
    pub degraded_comms_dbw_brake: bool,
    pub degraded_comms_dbw_gear: bool,
    pub degraded_internal: bool,
    pub degraded_control_performance: bool,
    pub degraded_param_mismatch: bool,
    pub degraded_vehicle: bool,
    pub degraded_vehicle_speed: bool,
    pub degraded_aped_feedback: bool,
    pub degraded_actuator_pedal_sensor: bool,
    pub degraded_sensor: bool,
    pub degraded_calibration: bool,
    pub fault: bool,
    pub fault_power: bool,
    pub fault_comms: bool,
    pub fault_comms_dbw: bool,
    pub fault_comms_dbw_gateway: bool,
    pub fault_comms_dbw_steer: bool,
    pub fault_comms_dbw_brake: bool,
    pub fault_comms_dbw_gear: bool,
    pub fault_internal: bool,
    pub fault_vehicle: bool,
    pub fault_vehicle_speed: bool,
    pub fault_sensor: bool,
    pub fault_aped_sensor_1: bool,
    pub fault_aped_sensor_2: bool,
    pub fault_aped_sensor_mismatch: bool,
    pub fault_actuator_pedal_sensor: bool,
    pub fault_control_performance: bool,
    pub fault_param_mismatch: bool,
    pub fault_param_limits: bool,
    pub fault_calibration: bool,
}

impl Default for ThrottleDiagnostics {
    fn default() -> Self {
        ThrottleDiagnostics {
            header: crate::std_msgs::msg::Header::default(),
            degraded: false,
            degraded_cmd_type: false,
            degraded_comms: false,
            degraded_comms_dbw: false,
            degraded_comms_dbw_gateway: false,
            degraded_comms_dbw_steer: false,
            degraded_comms_dbw_brake: false,
            degraded_comms_dbw_gear: false,
            degraded_internal: false,
            degraded_control_performance: false,
            degraded_param_mismatch: false,
            degraded_vehicle: false,
            degraded_vehicle_speed: false,
            degraded_aped_feedback: false,
            degraded_actuator_pedal_sensor: false,
            degraded_sensor: false,
            degraded_calibration: false,
            fault: false,
            fault_power: false,
            fault_comms: false,
            fault_comms_dbw: false,
            fault_comms_dbw_gateway: false,
            fault_comms_dbw_steer: false,
            fault_comms_dbw_brake: false,
            fault_comms_dbw_gear: false,
            fault_internal: false,
            fault_vehicle: false,
            fault_vehicle_speed: false,
            fault_sensor: false,
            fault_aped_sensor_1: false,
            fault_aped_sensor_2: false,
            fault_aped_sensor_mismatch: false,
            fault_actuator_pedal_sensor: false,
            fault_control_performance: false,
            fault_param_mismatch: false,
            fault_param_limits: false,
            fault_calibration: false,
        }
    }
}

impl crate::Message for ThrottleDiagnostics {}
