[package]
name = "ros2-nav-msgs"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true }
ros2-std-msgs = { workspace = true }
ros2-geometry-msgs = { workspace = true }
ros2_builtin_interfaces = "0.1.0"
