use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ActiveFaultLatched1 {
    pub header: crate::std_msgs::msg::Header,
    pub active_flt_latched_byte7_bit7: bool,
    pub active_flt_latched_byte7_bit6: bool,
    pub active_flt_latched_byte7_bit5: bool,
    pub active_flt_latched_byte7_bit4: bool,
    pub arm_to_dsp_chksum_fault: bool,
    pub dsp_to_arm_chksum_fault: bool,
    pub host_to_arm_chksum_fault: bool,
    pub arm_to_host_chksum_fault: bool,
    pub loop_bw_out_of_range: bool,
    pub dsp_overrun_fault: bool,
    pub active_flt_latched_byte6_bit5: bool,
    pub tuning_sensitivity_fault: bool,
    pub saturated_tuning_freq_fault: bool,
    pub local_osc_power_fault: bool,
    pub transmitter_power_fault: bool,
    pub active_flt_latched_byte6_bit0: bool,
    pub active_flt_latched_byte5_bit7: bool,
    pub active_flt_latched_byte5_bit6: bool,
    pub xcvr_device_spi_fault: bool,
    pub freq_synthesizer_spi_fault: bool,
    pub analog_converter_devic_spi_fault: bool,
    pub side_lobe_blockage: bool,
    pub active_flt_latched_byte5_bit1: bool,
    pub mnr_blocked: bool,
    pub ecu_temp_high_fault: bool,
    pub transmitter_temp_high_fault: bool,
    pub alignment_routine_failed_fault: bool,
    pub unreasonable_radar_data: bool,
    pub microprocessor_temp_high_fault: bool,
    pub vertical_alignment_out_of_range: bool,
    pub horizontal_alignment_out_of_range: bool,
    pub factory_alignment_mode: bool,
    pub battery_low_fault: bool,
    pub battery_high_fault: bool,
    pub v_1p25_supply_out_of_range: bool,
    pub active_flt_latched_byte3_bit4: bool,
    pub thermistor_out_of_range: bool,
    pub v_3p3_dac_supply_out_of_range: bool,
    pub v_3p3_raw_supply_out_of_range: bool,
    pub v_5_supply_out_of_range: bool,
    pub transmitter_id_fault: bool,
    pub active_flt_latched_byte2_bit6: bool,
    pub active_flt_latched_byte2_bit5: bool,
    pub active_flt_latched_byte2_bit4: bool,
    pub active_flt_latched_byte2_bit3: bool,
    pub active_flt_latched_byte2_bit2: bool,
    pub pcan_missing_msg_fault: bool,
    pub pcan_bus_off: bool,
    pub active_flt_latched_byte1_bit7: bool,
    pub active_flt_latched_byte1_bit6: bool,
    pub instruction_set_check_fault: bool,
    pub stack_overflow_fault: bool,
    pub watchdog_fault: bool,
    pub pll_lock_fault: bool,
    pub active_flt_latched_byte1_bit1: bool,
    pub ram_memory_test_fault: bool,
    pub usc_validation_fault: bool,
    pub active_flt_latched_byte0_bit6: bool,
    pub active_flt_latched_byte0_bit5: bool,
    pub active_flt_latched_byte0_bit4: bool,
    pub active_flt_latched_byte0_bit3: bool,
    pub keep_alive_checksum_fault: bool,
    pub program_calibration_flash_checksum: bool,
    pub application_flash_checksum_fault: bool,
}

impl Default for ActiveFaultLatched1 {
    fn default() -> Self {
        ActiveFaultLatched1 {
            header: crate::std_msgs::msg::Header::default(),
            active_flt_latched_byte7_bit7: false,
            active_flt_latched_byte7_bit6: false,
            active_flt_latched_byte7_bit5: false,
            active_flt_latched_byte7_bit4: false,
            arm_to_dsp_chksum_fault: false,
            dsp_to_arm_chksum_fault: false,
            host_to_arm_chksum_fault: false,
            arm_to_host_chksum_fault: false,
            loop_bw_out_of_range: false,
            dsp_overrun_fault: false,
            active_flt_latched_byte6_bit5: false,
            tuning_sensitivity_fault: false,
            saturated_tuning_freq_fault: false,
            local_osc_power_fault: false,
            transmitter_power_fault: false,
            active_flt_latched_byte6_bit0: false,
            active_flt_latched_byte5_bit7: false,
            active_flt_latched_byte5_bit6: false,
            xcvr_device_spi_fault: false,
            freq_synthesizer_spi_fault: false,
            analog_converter_devic_spi_fault: false,
            side_lobe_blockage: false,
            active_flt_latched_byte5_bit1: false,
            mnr_blocked: false,
            ecu_temp_high_fault: false,
            transmitter_temp_high_fault: false,
            alignment_routine_failed_fault: false,
            unreasonable_radar_data: false,
            microprocessor_temp_high_fault: false,
            vertical_alignment_out_of_range: false,
            horizontal_alignment_out_of_range: false,
            factory_alignment_mode: false,
            battery_low_fault: false,
            battery_high_fault: false,
            v_1p25_supply_out_of_range: false,
            active_flt_latched_byte3_bit4: false,
            thermistor_out_of_range: false,
            v_3p3_dac_supply_out_of_range: false,
            v_3p3_raw_supply_out_of_range: false,
            v_5_supply_out_of_range: false,
            transmitter_id_fault: false,
            active_flt_latched_byte2_bit6: false,
            active_flt_latched_byte2_bit5: false,
            active_flt_latched_byte2_bit4: false,
            active_flt_latched_byte2_bit3: false,
            active_flt_latched_byte2_bit2: false,
            pcan_missing_msg_fault: false,
            pcan_bus_off: false,
            active_flt_latched_byte1_bit7: false,
            active_flt_latched_byte1_bit6: false,
            instruction_set_check_fault: false,
            stack_overflow_fault: false,
            watchdog_fault: false,
            pll_lock_fault: false,
            active_flt_latched_byte1_bit1: false,
            ram_memory_test_fault: false,
            usc_validation_fault: false,
            active_flt_latched_byte0_bit6: false,
            active_flt_latched_byte0_bit5: false,
            active_flt_latched_byte0_bit4: false,
            active_flt_latched_byte0_bit3: false,
            keep_alive_checksum_fault: false,
            program_calibration_flash_checksum: false,
            application_flash_checksum_fault: false,
        }
    }
}

impl crate::Message for ActiveFaultLatched1 {}
