use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct UBXNavPVT {
    pub header: crate::std_msgs::msg::Header,
    pub itow: u32,
    pub year: u16,
    pub month: u8,
    pub day: u8,
    pub hour: u8,
    pub min: u8,
    pub sec: u8,
    pub valid_date: bool,
    pub valid_time: bool,
    pub fully_resolved: bool,
    pub valid_mag: bool,
    pub t_acc: u32,
    pub nano: i32,
    pub gps_fix: crate::ublox_ubx_msgs::msg::GpsFix,
    pub gnss_fix_ok: bool,
    pub diff_soln: bool,
    pub psm: crate::ublox_ubx_msgs::msg::PSMPVT,
    pub head_veh_valid: bool,
    pub carr_soln: crate::ublox_ubx_msgs::msg::CarrSoln,
    pub confirmed_avail: bool,
    pub confirmed_date: bool,
    pub confirmed_time: bool,
    pub num_sv: u8,
    pub lon: i32,
    pub lat: i32,
    pub height: i32,
    pub hmsl: i32,
    pub h_acc: u32,
    pub v_acc: u32,
    pub vel_n: i32,
    pub vel_e: i32,
    pub vel_d: i32,
    pub g_speed: i32,
    pub head_mot: i32,
    pub s_acc: u32,
    pub head_acc: u32,
    pub p_dop: u16,
    pub invalid_llh: bool,
    pub head_veh: i32,
    pub mag_dec: i16,
    pub mag_acc: u16,
}

impl Default for UBXNavPVT {
    fn default() -> Self {
        UBXNavPVT {
            header: crate::std_msgs::msg::Header::default(),
            itow: 0,
            year: 0,
            month: 0,
            day: 0,
            hour: 0,
            min: 0,
            sec: 0,
            valid_date: false,
            valid_time: false,
            fully_resolved: false,
            valid_mag: false,
            t_acc: 0,
            nano: 0,
            gps_fix: crate::ublox_ubx_msgs::msg::GpsFix::default(),
            gnss_fix_ok: false,
            diff_soln: false,
            psm: crate::ublox_ubx_msgs::msg::PSMPVT::default(),
            head_veh_valid: false,
            carr_soln: crate::ublox_ubx_msgs::msg::CarrSoln::default(),
            confirmed_avail: false,
            confirmed_date: false,
            confirmed_time: false,
            num_sv: 0,
            lon: 0,
            lat: 0,
            height: 0,
            hmsl: 0,
            h_acc: 0,
            v_acc: 0,
            vel_n: 0,
            vel_e: 0,
            vel_d: 0,
            g_speed: 0,
            head_mot: 0,
            s_acc: 0,
            head_acc: 0,
            p_dop: 0,
            invalid_llh: false,
            head_veh: 0,
            mag_dec: 0,
            mag_acc: 0,
        }
    }
}

impl crate::Message for UBXNavPVT {}
